// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sudokuData;

#nullable disable

namespace sudokuData.Migrations
{
    [DbContext(typeof(GrilleDbContext))]
    [Migration("20230627072010_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Grille.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Contenu")
                        .HasColumnType("int");

                    b.Property<int?>("LigneId")
                        .HasColumnType("int");

                    b.Property<int>("Num_Block")
                        .HasColumnType("int");

                    b.Property<int>("Num_Colonne")
                        .HasColumnType("int");

                    b.Property<int>("Num_Rangee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LigneId");

                    b.ToTable("Case");
                });

            modelBuilder.Entity("Grille.Models.Grille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Grille");
                });

            modelBuilder.Entity("Grille.Models.Ligne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GrilleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrilleId");

                    b.ToTable("Ligne");
                });

            modelBuilder.Entity("Grille.Models.Case", b =>
                {
                    b.HasOne("Grille.Models.Ligne", null)
                        .WithMany("Cases")
                        .HasForeignKey("LigneId");
                });

            modelBuilder.Entity("Grille.Models.Ligne", b =>
                {
                    b.HasOne("Grille.Models.Grille", null)
                        .WithMany("Rangees")
                        .HasForeignKey("GrilleId");
                });

            modelBuilder.Entity("Grille.Models.Grille", b =>
                {
                    b.Navigation("Rangees");
                });

            modelBuilder.Entity("Grille.Models.Ligne", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
